Repository berachain/beacon-kit, pull requests merged in 2024-06, with the labels that each got.

#1499 perf(sha256): Re-use hasher to reduce mallocs
  beacond/go.mod
  beacond/go.sum
  mod/node-core/go.mod
  mod/node-core/go.sum
  mod/primitives/pkg/crypto/sha256/sha256.go
  mod/primitives/pkg/eip4844/kzg_commitment.go
  mod/primitives/pkg/eip4844/kzg_commitment_test.go
  mod/primitives/pkg/merkle/proof.go
  mod/primitives/pkg/merkle/tree.go
  mod/primitives/pkg/merkle/zero/zero.go
  mod/primitives/pkg/ssz/merkle/index.go
  mod/primitives/pkg/ssz/merkleize_test.go
  mod/primitives/pkg/ssz/serialization_test.go
  mod/state-transition/go.mod
  mod/state-transition/go.sum
  mod/state-transition/pkg/core/state_processor_randao.go
Labels: Ready for Review

#1554 chore(go): Update dependency versions for correct build
  beacond/go.mod
  beacond/go.sum
  mod/cli/go.mod
  mod/cli/go.sum
  mod/config/go.mod
  mod/config/go.sum
  mod/node-core/go.mod
  mod/node-core/go.sum
Labels: Merge me daddy

#1594 perf(ssz): setup buffers for memory re-use
  mod/primitives/pkg/merkle/buffer.go
  mod/primitives/pkg/merkle/buffer_test.go
  mod/primitives/pkg/merkle/hasher.go
  mod/primitives/pkg/merkle/hasher_test.go
  mod/primitives/pkg/merkle/interfaces.go
  mod/primitives/pkg/merkle/root.go
  mod/primitives/pkg/merkle/root_test.go
  mod/primitives/pkg/merkle/tree.go
  mod/primitives/pkg/merkle/tree_test.go
  mod/primitives/pkg/ssz/helpers.go
  mod/primitives/pkg/ssz/merkle/tree.go
  mod/primitives/pkg/ssz/merkle/tree_test.go
  mod/primitives/pkg/ssz/merkleize.go
  mod/state-transition/pkg/core/state_processor.go
Labels: Ready for Review

#1619 perf(ssz): Re-use merkleizer for calculating txs roots
  mod/consensus-types/pkg/types/payload.go
  mod/consensus-types/pkg/types/payload_test.go
  mod/engine-primitives/pkg/engine-primitives/transactions.go
  mod/primitives/pkg/ssz/merkleizer.go
  mod/state-transition/pkg/core/state_processor.go
  mod/state-transition/pkg/core/state_processor_payload.go
  mod/state-transition/pkg/core/types.go
Labels: Merge me daddy, Ready for Review

#1637 perf(ssz): remove bytes buffer from hasher
  mod/primitives/pkg/crypto/hasher.go
  mod/primitives/pkg/crypto/mocks/hash_fn.mock.go
  mod/primitives/pkg/crypto/mocks/hasher.mock.go
  mod/primitives/pkg/crypto/sha256/sha256.go
  mod/primitives/pkg/eip4844/kzg_commitment.go
  mod/primitives/pkg/merkle/hasher.go
  mod/primitives/pkg/merkle/hasher_test.go
  mod/primitives/pkg/merkle/proof.go
  mod/primitives/pkg/merkle/tree.go
  mod/primitives/pkg/merkle/types.go
  mod/primitives/pkg/merkle/zero/zero.go
  mod/primitives/pkg/ssz/index.go
  mod/primitives/pkg/ssz/merkleizer/merkleizer.go
  mod/state-transition/pkg/core/state_processor_randao.go
  mod/storage/go.mod
  mod/storage/go.sum
Labels: Merge me daddy, Ready for Review

#1655 chore(cli): non breaking change
  mod/cli/pkg/commands/deposit/create.go
  mod/cli/pkg/commands/genesis/deposit.go
Labels: skill issue
