Repository berachain/beacon-kit, pull requests merged in 2024-07, with the labels that each got.

#1690 test(merkle): fuzz testing large inputs on parallelized root hasher
  beacond/go.sum
  mod/cli/go.sum
  mod/config/go.sum
  mod/consensus-types/go.sum
  mod/consensus/go.sum
  mod/node-core/go.sum
  mod/primitives/go.mod
  mod/primitives/pkg/merkle/hasher.go
  mod/primitives/pkg/merkle/hasher_fuzz_test.go
  mod/primitives/pkg/merkle/hasher_test.go
  mod/runtime/go.sum
  mod/storage/go.sum
Labels: not breaking

#1693 test(ssz): conformance tests for merkleizing byte lists/vectors
  mod/engine-primitives/pkg/engine-primitives/transactions_test.go
  mod/primitives/pkg/bytes/b96_test.go
  mod/primitives/pkg/ssz/merkleizer/merkleizer.go
  mod/primitives/pkg/ssz/merkleizer/merkleizer_basic_test.go
  mod/primitives/pkg/ssz/merkleizer/merkleizer_bytes_test.go
Labels: Merge me daddy, not breaking

#1700 perf(merkle): enable parallelized hasher
  beacond/go.mod
  beacond/go.sum
  build/tools/go.mod
  build/tools/go.sum
  mod/cli/go.mod
  mod/cli/go.sum
  mod/execution/go.mod
  mod/execution/go.sum
  mod/geth-primitives/go.mod
  mod/geth-primitives/go.sum
  mod/node-core/go.mod
  mod/node-core/go.sum
  mod/primitives/go.mod
  mod/primitives/pkg/merkle/hasher.go
  mod/primitives/pkg/merkle/hasher_fuzz_test.go
  mod/primitives/pkg/merkle/hasher_test.go
  testing/go.mod
  testing/go.sum
Labels: Ready for Review

#1710 chore(merkle): Re-use bytes buffer for merkle hasher
  mod/primitives/pkg/bytes/buffer/buffer.go
  mod/primitives/pkg/merkle/hasher.go
  mod/primitives/pkg/merkle/hasher_test.go
Labels: Merge me daddy, Ready for Review

#1735 Kurtosis clean up
  kurtosis/src/constants.star
  kurtosis/src/nodes/execution/execution.star
  kurtosis/src/nodes/execution/reth/config.star
Labels: Ready for Review

#1519 add otterscan to kurtosis
  kurtosis/beaconkit-all.yaml
  kurtosis/main.star
  kurtosis/src/lib/service_config.star
  kurtosis/src/nodes/execution/erigon/config.star
  kurtosis/src/nodes/execution/execution.star
  kurtosis/src/services/otterscan/launcher.star
Labels: Ready for Review

#1800 feat(eip4788): Beacon Block Prover Contract
  contracts/src/eip4788/BeaconVerifier.sol
  contracts/src/eip4788/SSZ.sol
  contracts/src/eip4788/ValidatorVerifier.sol
  contracts/src/eip4788/Verifier.sol
  contracts/src/eip4788/WithdrawalsVerifier.sol
  contracts/src/eip4788/interfaces/IBeaconVerifier.sol
  contracts/test/eip4788/SSZ.t.sol
  contracts/test/eip4788/ValidatorVerifier.t.sol
  contracts/test/eip4788/WithdrawalsVerifier.t.sol
  contracts/test/eip4788/fixtures/validator_proof.json
  contracts/test/eip4788/fixtures/withdrawal_proof.json
Labels: Merge me daddy, Ready for Review

#1812 feat(node-api): Use state processor to return the corrected beacon state on backend
  mod/node-api/backend/backend.go
  mod/node-api/backend/block.go
  mod/node-api/backend/genesis.go
  mod/node-api/backend/mocks/beacon_state.mock.go
  mod/node-api/backend/mocks/state_processor.mock.go
  mod/node-api/backend/randao.go
  mod/node-api/backend/state.go
  mod/node-api/backend/types.go
  mod/node-api/backend/validator.go
  mod/node-api/handlers/proof/backend.go
  mod/node-api/handlers/proof/block.go
  mod/node-api/handlers/proof/handler.go
  mod/node-api/handlers/proof/merkle/execution.go
  mod/node-api/handlers/proof/merkle/proposer.go
  mod/node-api/handlers/proof/types/types.go
  mod/node-core/pkg/components/api.go
  mod/node-core/pkg/components/chain_service.go
  mod/node-core/pkg/components/state_processor.go
  mod/node-core/pkg/components/storage/storage.go
  mod/node-core/pkg/components/types.go
  mod/node-core/pkg/components/validator_service.go
  mod/state-transition/pkg/core/state/statedb.go
Labels: Merge me daddy, Ready for Review
