Repository berachain/beacon-kit, pull requests merged in 2025-01, with the labels that each got.

#2393 1/2 fix(cli): Align `genesis validator-root` cmd with processing of genesis validators
  cli/commands/genesis/root.go
  cli/commands/genesis/root_test.go
  state-transition/core/core_test.go
  state-transition/core/state_processor_genesis_test.go
  state-transition/core/state_processor_staking_test.go
  state-transition/core/validation_deposits_test.go
  testing/state-transition/README.md
  testing/state-transition/state-transition.go
Labels: Merge me daddy, Ready for Review

#2383 chore(kurtosis): kurtosis setup to get deposit contract storage slots and fill genesis files
  Dockerfile
  kurtosis/main.star
  kurtosis/src/networks/kurtosis-devnet/network-configs/genesis.json.template
  kurtosis/src/nodes/consensus/beacond/launcher.star
  kurtosis/src/nodes/consensus/beacond/scripts/modify-genesis-with-deposits.sh
  kurtosis/src/nodes/consensus/beacond/scripts/multiple-premined-deposits-cl.sh
  kurtosis/src/nodes/execution/nethermind/genesis.json.template
  kurtosis/src/nodes/nodes.star
  testing/e2e/e2e_staking_test.go
Labels: Merge me daddy

#2413 fix(initchain): Enforce stricter handling on InitChain Requests
  consensus/cometbft/service/init_chain.go
Labels: Ready for Review

#2402 chore(genesis deposit) : Change in local network setup with single node
  README.md
  scripts/build/testing.mk
  testing/files/entrypoint.sh
Labels: Ready for Review

#2398 chore(e2e): Add verification during deposit e2e test
  node-api/backend/validator.go
  node-api/handlers/beacon/types/conversions.go
  node-api/handlers/beacon/types/response.go
  scripts/build/testing.mk
  testing/e2e/e2e_staking_test.go
  testing/e2e/suite/setup.go
Labels: Merge me daddy, Ready for Review

#2423 [4/n] refactor(chain-spec): handling values for planned fork upgrades
  beacon/validator/block_builder.go
  chain/data.go
  chain/helpers.go
  chain/helpers_test.go
  chain/spec.go
  cli/commands/deposit/commands_test.go
  cli/utils/genesis/root_test.go
  config/spec/base.go
  config/spec/boonet.go
  config/spec/chain_ids.go
  config/spec/defaults.go
  config/spec/defaults_test.go
  config/spec/devnet.go
  config/spec/mainnet.go
  config/spec/testnet.go
  consensus-types/types/body.go
  consensus-types/types/body_test.go
  consensus-types/types/genesis.go
  consensus-types/types/genesis_test.go
  consensus-types/types/payload.go
  consensus-types/types/signed_beacon_block_test.go
  da/types/sidecar_test.go
  kurtosis/src/nodes/consensus/beacond/scripts/modify-genesis-with-deposits.sh
  node-api/handlers/debug/backend.go
  node-api/handlers/debug/state.go
  node-api/handlers/proof/merkle/execution_fee_recipient.go
  node-api/handlers/proof/merkle/execution_number.go
  node-core/components/chain_spec.go
  scripts/build/testing.mk
  state-transition/core/core_test.go
  state-transition/core/state_processor_genesis_test.go
  state-transition/core/state_processor_randao.go
  state-transition/core/state_processor_staking_test.go
  state-transition/core/validation_deposits_test.go
  testing/e2e/e2e_staking_test.go
  testing/state-transition/state-transition.go
Labels: Ready for Review

#2426 feat(cli): Tool to display all formats of public key
  cli/commands/deposit/commands.go
  cli/commands/deposit/keys.go
Labels: Merge me daddy, Ready for Review

#2407 fix(deposits): Enforce deposit inclusion
  state-transition/core/validation_deposits.go
Labels: Merge me daddy, Ready for Review

#2412 chore(block-builder): a few minor cleanups
  beacon/validator/block_builder.go
  beacon/validator/errors.go
  beacon/validator/service.go
  beacon/validator/types.go
  config/template/template.go
  execution/client/client.go
  execution/client/ethclient/engine.go
  execution/client/ethclient/engine_test.go
  execution/client/ethclient/ethclient.go
  execution/client/ethclient/rpc/client.go
  execution/client/ethclient/rpc/header.go
  execution/client/ethclient/rpc/options.go
  node-core/components/validator_service.go
  payload/builder/payload.go
Labels: Ready for Review

#2442 fix(flags): Fix Payload Builder Flags
  cli/flags/flags.go
Labels: Ready for Review

#2446 refactor(deposit-storage): Refactor set-deposit-storage and execution-payload to be callable in Runtime
  cli/commands/genesis/payload.go
  cli/commands/genesis/storage.go
Labels: Ready for Review

#2437 chore(types): Introduce canonical sorting of common.Version
  beacon/validator/block_builder.go
  chain/helpers.go
  chain/helpers_test.go
  chain/spec.go
  cli/commands/deposit/create.go
  cli/commands/deposit/validate.go
  cli/commands/genesis/deposit.go
  cli/commands/genesis/payload.go
  cli/utils/genesis/root_test.go
  cli/utils/parser/errors.go
  consensus-types/types/block.go
  consensus-types/types/block_test.go
  consensus-types/types/body_test.go
  consensus-types/types/genesis.go
  consensus-types/types/genesis_test.go
  consensus-types/types/payload.go
  consensus-types/types/payload_header.go
  consensus-types/types/payload_header_test.go
  consensus-types/types/payload_requests.go
  consensus-types/types/payload_requests_test.go
  consensus-types/types/payload_test.go
  consensus-types/types/signed_beacon_block.go
  consensus-types/types/signed_beacon_block_test.go
  consensus/cometbft/service/encoding/encoding.go
  da/blob/types.go
  da/types/sidecar_test.go
  engine-primitives/engine-primitives/attributes.go
  engine-primitives/engine-primitives/attributes_test.go
  execution/client/engine.go
  execution/client/ethclient/engine.go
  execution/client/ethclient/engine_test.go
  primitives/bytes/b4_test.go
  primitives/constants/misc.go
  primitives/constraints/basic.go
  primitives/version/comparable.go
  primitives/version/comparable_test.go
  primitives/version/versions.go
  state-transition/core/core_test.go
  state-transition/core/state_processor_genesis.go
  state-transition/core/state_processor_genesis_test.go
  state-transition/core/state_processor_randao.go
  state-transition/core/state_processor_signature.go
  state-transition/core/state_processor_staking.go
  state-transition/core/state_processor_staking_test.go
  state-transition/core/validation_deposits_test.go
  storage/beacondb/eth1.go
  storage/encoding/ssz.go
Labels: Merge me daddy
