Repository berachain/beacon-kit, pull requests merged in 2025-05, with the labels that each got.

#2723 fix(pectra): Spec Alignment for ExpectedWithdrawals
  state-transition/core/state/statedb.go
Labels: Ready for Review

#2731 chore(pectra): Update comments based on Bectra changes
  consensus/cometbft/service/finalize_block.go
  primitives/eip7002/withdrawal.go
  state-transition/core/README.md
  state-transition/core/state_processor.go
Labels: Merge me daddy, Ready for Review

#2738 fix(bash): use env bash
  kurtosis/src/nodes/consensus/beacond/scripts/modify-genesis-with-deposits.sh
  kurtosis/src/nodes/consensus/beacond/scripts/multiple-premined-deposits-cl.sh
  scripts/build/golines.sh
  scripts/rollback_cl.sh
  testing/files/entrypoint.sh
Labels: Merge me daddy

#2720 refactor: use slices.Contains to simplify code
  errors/mod.go
Labels: Merge me daddy

#2713 tests(pectra): More Simulation Tests for Pectra
  execution/requests/eip7002/interfaces.go
  execution/requests/eip7002/withdrawal.go
  execution/requests/eip7002/withdrawal_test.go
  execution/requests/eip7251/consolidation.go
  execution/requests/eip7251/interfaces.go
  state-transition/core/state_processor_validators.go
  testing/simulated/components.go
  testing/simulated/el-genesis-files/pectra-eth-genesis.json
  testing/simulated/el-genesis-files/pectra-fork-genesis.json
  testing/simulated/execution/execnode.go
  testing/simulated/homedir.go
  testing/simulated/malicious_consensus_test.go
  testing/simulated/malicious_proposer_test.go
  testing/simulated/pectra_fork_test.go
  testing/simulated/pectra_genesis_test.go
  testing/simulated/pectra_withdrawal_test.go
  testing/simulated/simulated_test.go
  testing/simulated/testnode.go
  testing/simulated/transformers.go
  testing/simulated/utils.go
Labels: Ready for Review

#2740 node-api: partial pending withdrawals
  kurtosis/src/nodes/consensus/beacond/node.star
  node-api/backend/withdrawal.go
  node-api/handlers/beacon/backend.go
  node-api/handlers/beacon/routes.go
  node-api/handlers/beacon/types/request.go
  node-api/handlers/beacon/types/response.go
  node-api/handlers/beacon/withdrawal.go
  node-core/components/interfaces.go
  testing/e2e/e2e_withdrawal_test.go
Labels: Ready for Review

#2780 fix(test): Fix Deposit Contract Predeploy Code
  kurtosis/src/networks/kurtosis-devnet/network-configs/genesis.json.template
  kurtosis/src/nodes/execution/nethermind/genesis.json.template
  testing/e2e/e2e_staking_test.go
  testing/e2e/suite/setup.go
  testing/files/eth-genesis.json
  testing/files/eth-nether-genesis.json
  testing/simulated/el-genesis-files/eth-genesis.json
  testing/simulated/el-genesis-files/pectra-eth-genesis.json
  testing/simulated/el-genesis-files/pectra-fork-genesis.json
Labels: Ready for Review

#2783 chore(deposits): Add Metric and Log for Excess Balance Withdrawal
  state-transition/core/state/metrics.go
  state-transition/core/state/statedb.go
  testing/simulated/pectra_withdrawal_test.go
Labels: Ready for Review

#2734 pre-deploys to the genesis files for nethermind
  kurtosis/src/nodes/execution/nethermind/genesis.json.template
  scripts/build/testing.mk
  testing/files/eth-nether-genesis.json
Labels: Ready for Review

#2778 chore(storage): Consolidate deposits storage 1/3
  beacon/blockchain/interfaces.go
  beacon/blockchain/payload_test.go
  beacon/validator/block_builder.go
  beacon/validator/interfaces.go
  node-api/backend/mocks/storage_backend.mock.go
  node-core/components/backend.go
  node-core/components/deposit_store.go
  node-core/components/interfaces.go
  node-core/components/state_processor.go
  node-core/components/storage/storage.go
  state-transition/core/state_processor.go
  state-transition/core/state_processor_payload_test.go
  state-transition/core/state_processor_staking_test.go
  state-transition/core/state_processor_withdrawals_test.go
  state-transition/core/validation_deposits.go
  state-transition/core/validation_deposits_test.go
  storage/deposit/common/synced_db.go
  storage/deposit/store.go
  storage/deposit/v1/provider.go
  storage/deposit/v1/store.go
  storage/deposit/v1/store_test.go
  testing/simulated/pectra_withdrawal_test.go
  testing/simulated/utils.go
  testing/state-transition/state-transition.go
Labels: Ready for Review
