Repository berachain/beacon-kit, pull requests merged in 2025-04, with the labels that each got.

#2647 [2/2] chore(ssz): merkle libraries cleanup
  node-api/handlers/proof/merkle/beacon_state.go
  node-api/handlers/proof/merkle/block_proposer_index.go
  node-api/handlers/proof/merkle/block_proposer_pubkey.go
  node-api/handlers/proof/merkle/constants_test.go
  node-api/handlers/proof/merkle/execution_fee_recipient.go
  node-api/handlers/proof/merkle/execution_number.go
  primitives/encoding/ssz/constants/constants.go
  primitives/encoding/ssz/db/node.go
  primitives/encoding/ssz/db/node_test.go
  primitives/encoding/ssz/merkle/errors.go
  primitives/encoding/ssz/merkle/proof.go
  primitives/encoding/ssz/merkle/tree.go
  primitives/encoding/ssz/merkle/tree_test.go
  primitives/encoding/ssz/schema/common.go
  primitives/encoding/ssz/schema/definitions.go
  primitives/encoding/ssz/schema/id.go
  primitives/merkle/index.go
  primitives/merkle/index_test.go
  primitives/merkle/object_path.go
  primitives/merkle/object_path_test.go
  primitives/merkle/root_hasher.go
  primitives/merkle/root_hasher_test.go
  primitives/merkle/tree.go
Labels: Ready for Review

#2601 feat(node-api): genesis api
  node-api/backend/backend.go
  node-api/backend/backend_test.go
  node-api/backend/block.go
  node-api/backend/genesis.go
  node-api/backend/genesis_test.go
  node-api/backend/randao.go
  node-api/backend/state.go
  node-api/backend/validator.go
  node-api/backend/validator_test.go
  node-api/handlers/beacon/backend.go
  node-api/handlers/beacon/genesis.go
  node-core/components/api.go
  node-core/components/interfaces.go
  testing/e2e/e2e_api_test.go
  testing/e2e/suite/types/consensus_client.go
Labels: Merge me daddy, Ready for Review

#2657 chore(transition): Always process exactly one slot in `ProcessSlots`
  node-api/backend/validator_test.go
  state-transition/core/state_processor.go
  state-transition/core/state_processor_test.go
Labels: Ready for Review

#2656 [1/n] feat(pectra): Add Pending Partial Withdrawals to BeaconState
  consensus-types/types/pending_partial_withdrawal.go
  consensus-types/types/pending_partial_withdrawal_test.go
  consensus-types/types/state.go
  consensus-types/types/state_test.go
  node-api/handlers/proof/block_proposer.go
  node-api/handlers/proof/merkle/constants.go
  node-api/handlers/proof/merkle/mock/beacon_state.go
  node-api/handlers/proof/merkle/proposer_pubkey.go
  node-api/handlers/proof/merkle/proposer_pubkey_test.go
  node-api/handlers/proof/merkle/testdata/many_validators_proposer_pubkey_proof_deneb.json
  node-api/handlers/proof/merkle/testdata/one_validator_proposer_pubkey_proof_deneb.json
  node-api/handlers/proof/types/interfaces.go
  primitives/constants/operations_per_block.go
  state-transition/core/state/statedb.go
  storage/beacondb/keys/keys.go
  storage/beacondb/kvstore.go
  storage/beacondb/registry.go
  storage/beacondb/registry_test.go
Labels: Merge me daddy

#2678 [3/n] feat(pectra): Prepare beacon state for fork upgrade
  beacon/blockchain/interfaces.go
  beacon/blockchain/payload.go
  beacon/blockchain/process_proposal.go
  beacon/validator/block_builder.go
  beacon/validator/interfaces.go
  node-api/backend/backend.go
  node-api/backend/block.go
  node-api/backend/genesis.go
  node-api/backend/genesis_test.go
  node-api/backend/interfaces.go
  node-api/backend/randao.go
  node-api/backend/state.go
  node-api/backend/validator.go
  node-api/backend/validator_test.go
  node-api/handlers/beacon/backend.go
  node-api/handlers/beacon/historical.go
  node-api/handlers/debug/backend.go
  node-api/handlers/debug/state.go
  node-api/handlers/proof/backend.go
  node-api/handlers/proof/handler.go
  node-core/components/api.go
  node-core/components/interfaces.go
  primitives/version/name.go
  state-transition/core/interfaces.go
  state-transition/core/state/statedb.go
  state-transition/core/state_processor.go
  state-transition/core/state_processor_forks.go
  storage/beacondb/registry.go
  testing/e2e/e2e_proofs_test.go
Labels: Ready for Review

#2686 [4/n] feat(genesis): Remove version.Genesis and allow for different fork version in Genesis
  beacon/blockchain/execution_engine.go
  beacon/blockchain/init_chain.go
  beacon/blockchain/interfaces.go
  chain/data.go
  chain/helpers.go
  chain/spec.go
  cli/commands/deposit/create.go
  cli/commands/deposit/interfaces.go
  cli/commands/deposit/validate.go
  cli/commands/genesis/deposit.go
  cli/commands/genesis/interfaces.go
  cli/commands/genesis/payload.go
  cli/commands/initialize/initialize.go
  cli/commands/server/types/chainspec.go
  cli/commands/server/types/mainnet_spec.toml
  cli/commands/setup.go
  cli/utils/genesis/root_test.go
  config/spec/devnet.go
  config/spec/mainnet.go
  config/spec/testnet.go
  consensus-types/types/genesis.go
  consensus-types/types/genesis_test.go
  consensus-types/types/payload_header.go
  consensus/cometbft/service/genesis.go
  node-api/backend/genesis_test.go
  node-api/backend/validator_test.go
  node-core/components/interfaces.go
  primitives/version/versions.go
  scripts/build/linting.mk
  state-transition/core/core_test.go
  state-transition/core/interfaces.go
  state-transition/core/state_processor_forks.go
  state-transition/core/state_processor_genesis.go
  state-transition/core/state_processor_genesis_test.go
  state-transition/core/state_processor_payload_test.go
  state-transition/core/state_processor_staking.go
  state-transition/core/state_processor_staking_test.go
  state-transition/core/state_processor_test.go
  state-transition/core/validation_deposits_test.go
  storage/beacondb/eth1.go
  testing/simulated/components.go
  testing/simulated/homedir.go
Labels: Ready for Review

#2655 [5/n] feat(pectra): Withdrawals Support
  beacon/validator/block_builder.go
  chain/data.go
  chain/spec.go
  cli/commands/server/types/chainspec.go
  cli/commands/server/types/mainnet_spec.toml
  cli/utils/genesis/root.go
  config/spec/defaults.go
  config/spec/devnet.go
  config/spec/mainnet.go
  consensus-types/types/body.go
  consensus-types/types/execution_requests.go
  consensus-types/types/pending_partial_withdrawal.go
  consensus-types/types/signed_beacon_block.go
  consensus-types/types/signed_beacon_block_test.go
  consensus-types/types/state.go
  consensus-types/types/validator.go
  consensus-types/types/validator_test.go
  kurtosis/src/networks/kurtosis-devnet/network-configs/genesis.json.template
  node-api/backend/mocks/beacon_state.mock.go
  node-api/backend/validator_test.go
  node-core/components/interfaces.go
  node-core/components/storage/storage.go
  payload/attributes/factory.go
  primitives/constants/misc.go
  primitives/constants/payload.go
  state-transition/core/core_test.go
  state-transition/core/state/interfaces.go
  state-transition/core/state/statedb.go
  state-transition/core/state_processor_exits.go
  state-transition/core/state_processor_genesis.go
  state-transition/core/state_processor_genesis_test.go
  state-transition/core/state_processor_staking.go
  state-transition/core/state_processor_staking_test.go
  state-transition/core/state_processor_validators.go
  state-transition/core/state_processor_withdrawals.go
  state-transition/core/validation_deposits_test.go
  testing/quick/compare_test.go
  testing/simulated/chaos_test.go
  testing/simulated/components.go
  testing/simulated/el-genesis-files/pectra-eth-genesis.json
  testing/simulated/el-genesis-files/pectra-fork-genesis.json
  testing/simulated/homedir.go
  testing/simulated/malicious_consensus_test.go
  testing/simulated/malicious_proposer_test.go
  testing/simulated/pectra_genesis_test.go
  testing/simulated/utils.go
  testing/simulated/valid_chain_test.go
Labels: Ready for Review

#2709 refactor(pectra): clean up code of new state processing
  chain/spec.go
  cli/utils/genesis/root.go
  node-api/backend/validator_test.go
  state-transition/core/interfaces.go
  state-transition/core/state/interfaces.go
  state-transition/core/state/statedb.go
  state-transition/core/state_processor.go
  state-transition/core/state_processor_exits.go
  state-transition/core/state_processor_genesis.go
  state-transition/core/state_processor_genesis_test.go
  state-transition/core/state_processor_payload.go
  state-transition/core/state_processor_payload_test.go
  state-transition/core/state_processor_randao.go
  state-transition/core/state_processor_staking.go
  state-transition/core/state_processor_staking_test.go
  state-transition/core/state_processor_test.go
  state-transition/core/state_processor_validators.go
  state-transition/core/state_processor_withdrawals.go
  state-transition/core/validation_deposits_test.go
  storage/beacondb/registry.go
  storage/beacondb/registry_test.go
  testing/e2e/e2e_inflation_test.go
  testing/simulated/homedir.go
  testing/simulated/pectra_genesis_test.go
Labels: Ready for Review

#2714 chore(state-processor): some more UTs
  state-transition/core/state_processor_withdrawals_test.go
Labels: Ready for Review

#2719 chore(pectra): Add Logger to StateDB so we can log in ExpectedWithdrawals
  node-api/backend/backend_test.go
  node-api/backend/genesis_test.go
  node-api/backend/validator_test.go
  node-core/components/backend.go
  node-core/components/storage/storage.go
  state-transition/core/state/statedb.go
  state-transition/core/state_processor_payload_test.go
  testing/state-transition/state-transition.go
Labels: Ready for Review
